version: "3"

services:
  rustapp:
    build: ./rust
    # volumes:
    #   - ./web:/usr/src/app
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - PASSWORD=alohamora
      - USE_HTTPS=false